### ISSUE TITLE
Niewłaściwa struktura dokumentu

### ISSUE THREAD

**Issue by mondoreale** [qwazs/Time#1]
Dokumentacja `<body>` mówi, że w dokumencie HTML tag ten może wystąpić tylko raz.
> _There can be only one <body> element in a document._

Więcej na temat `<body>` – https://developer.mozilla.org/pl/docs/Web/HTML/Element/body

—

Generalnie struktura dokumentu HTML to:

```html
<!doctype html>
<html>
  <head></head>
  <body></body>
</html>
```

PS. Więcej na temat `doctype` – http://how2html.pl/doctype-html/

Pozdro! — M.

**Comment by qwazs** [comment]
a teraz to już raczej lepiej

**Comment by mondoreale** [comment]
Zdecydowanie!
